#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Linux-Cpuinfo
version:      1.7
version_from: lib/Linux/Cpuinfo.pm
installdirs:  site
requires:
    Test::Simple:                  0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
